### ISSUE TITLE
doesn't use latest React tools

### ISSUE THREAD

**Issue by jmuffat** [gustavnikolaj/express-jsxtransform#3]
Partial solution:
I have modified module.json to depend on v.0.13.1 of react-tools and things sort of work ok for me now. It looks like it's just the changes in syntax making some tests fail during npm install:

  1) test server with jsxtransform should transform a js file with jsx content and jsx annotation
  2) test server with jsxtransform should transform a jsx file with jsx content and no jsx annotation
  3) test server with jsxtransform should transform a jsx file with jsx content and jsx annotation

Thanks
J.

**Comment by gustavnikolaj** [comment]
Sorry for the late reply. I'll look into updating the react-tools to the latest. I'll probably add it as a peerDepencency, so you can use them with whatever version unless the API breaks. That will prevent this situation from happening again.

I think the reason for the tests failing is some changes in the conventions around file names and file annotations that happened since I wrote this module.

**Comment by gustavnikolaj** [comment]
Released in v3.0.0 :-)

**Comment by jmuffat** [comment]
cheers !
