### ISSUE TITLE
The future of express-jsxtransform

### ISSUE THREAD

**Issue by gustavnikolaj** [gustavnikolaj/express-jsxtransform#6]
As I was made aware in https://github.com/Munter/generator-greenfield/issues/3 facebook no longer uses the jsxtransform module, but babel for their jsx transpilation needs.

I'm no longer using this module myself, but I'll be happy to make changes to it, to move it forward. I just need some advice from actual users.

Would it make sense, to just wrap babel and use that for transpilation of just JSX - if it is even possible to configure babel to do that - or would a full blown babel transpiler be called for? Does it even make sense to do that?

I would love some suggestions on how to move it forward.

/cc @Munter

**Comment by Munter** [comment]
I think the best forward path is to drop these individual asset type transpiler middlewares for a single one wrapping [https://github.com/Munter/tolk](tolk). That's where I'm going to focus my efforts, since fusile is already consuming it, middlewares can do so very easily as well, and Assetgraphs file reading could use it as well

**Comment by gustavnikolaj** [comment]
Deprecating the module, as babel + webpack is now the default way of using react and jsx. Updated the readme accordingly.

https://github.com/gustavnikolaj/express-jsxtransform/commit/4f52f3c0acbffbec9d6bf779caeed41e7713cb09
